# Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.tooling.parallel=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=true
# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
# Kotlin
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental=true
kotlin.incremental.multiplatform=true
kotlin.incremental.jvm.fir=true
